#!/usr/bin/env node
/**
 * Access bootstrap — the two rules that decide who can reach a kohlab at all.
 *
 * Run:  node scripts/check-access.mjs
 *
 *   1. A server bound beyond loopback, with no key and no users, must generate
 *      itself one. Without it an anonymous caller is the owner — the first person
 *      to find the port owns the box — and leaving that to a firewall the
 *      operator may not know they need is not a safety net.
 *   2. That convenience is kept on loopback, where the only caller is already on
 *      the machine.
 *
 * `kohlab key` is the way back in when the key is lost, so it is checked too: it
 * must find a key that was generated at startup, and rotate it.
 *
 * Each server runs on its own port with its own state directory and socket, so
 * this never touches a running deployment.
 */
import { spawn, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const tmp = mkdtempSync(join(tmpdir(), "kohlab-access-"));

let passed = 0;
const failures = [];

function check(name, condition, detail = "") {
  if (condition) {
    passed++;
    console.log(`  ok   ${name}`);
    return;
  }
  failures.push(name);
  console.log(`  FAIL ${name} ${detail}`);
}

/** Start the server and wait for it to answer, or give up. */
async function startServer({ port, works, host, extraEnv = {} }) {
  const dir = join(tmp, works);
  mkdirSync(dir, { recursive: true });
  const child = spawn("bun", ["run", "server.ts"], {
    cwd: ROOT,
    env: { ...process.env, PORT: String(port), HOST: host, WORKS_DIR: join(dir, "state"), PTY_SOCKET: join(dir, "pty.sock"), KOHLAB_KEY: "", ...extraEnv },
    stdio: ["ignore", "pipe", "pipe"],
  });
  let log = "";
  child.stdout.on("data", (d) => (log += d));
  child.stderr.on("data", (d) => (log += d));
  for (let i = 0; i < 60; i++) {
    const up = await fetch(`http://127.0.0.1:${port}/api/auth/required`).then((r) => r.ok).catch(() => false);
    if (up) return { child, dir, log: () => log };
    await new Promise((r) => setTimeout(r, 150));
  }
  child.kill("SIGKILL");
  throw new Error(`server on ${host}:${port} never came up\n${log}`);
}

function stopServer(s) {
  try {
    s.child.kill("SIGKILL");
  } catch {
    /* gone */
  }
  // the daemon is detached on purpose, so it needs finding by its own socket
  for (const pid of readdirOfProc()) {
    try {
      if (!readFileSync(`/proc/${pid}/cmdline`, "utf8").includes("pty-daemon.cjs")) continue;
      if (!readFileSync(`/proc/${pid}/environ`, "utf8").includes(`PTY_SOCKET=${join(s.dir, "pty.sock")}`)) continue;
      process.kill(Number(pid), "SIGTERM");
    } catch {
      /* not ours */
    }
  }
}

function readdirOfProc() {
  return spawnSync("ls", ["/proc"], { encoding: "utf8" }).stdout.split("\n").filter((p) => /^\d+$/.test(p));
}

/** The CLI, reading the same state directory as the server under test. */
function cli(stateDir, args) {
  const r = spawnSync("bun", ["run", join(ROOT, "cli.ts"), ...args], {
    encoding: "utf8",
    env: { ...process.env, WORKS_DIR: stateDir, KOHLAB_UNIT: "kohlab-not-here", KOHLAB_KEY: "" },
  });
  return { status: r.status, out: `${r.stdout ?? ""}${r.stderr ?? ""}` };
}

try {
  console.log("\nkohlab — access bootstrap\n");

  // ── bound beyond loopback, keyless: it must generate a key ────────────────
  const exposed = await startServer({ port: 7821, works: "exposed", host: "0.0.0.0" });
  try {
    const stateDir = join(exposed.dir, "state");
    const keyPath = join(stateDir, "key");
    check("a key was generated and stored", existsSync(keyPath), keyPath);
    if (existsSync(keyPath)) {
      const key = readFileSync(keyPath, "utf8").trim();
      check("the key looks like a key", /^[0-9a-f]{48}$/.test(key), key.slice(0, 12));
      check("it is not world-readable", (statSync(keyPath).mode & 0o077) === 0, (statSync(keyPath).mode & 0o777).toString(8));
      const anon = await fetch("http://127.0.0.1:7821/api/workspaces");
      check("anonymous callers are refused", anon.status === 401, `got ${anon.status}`);
      const withKey = await fetch(`http://127.0.0.1:7821/api/workspaces?key=${key}`);
      check("the generated key works", withKey.status === 200, `got ${withKey.status}`);
    }
    check("it says so in the log", /generated one/.test(exposed.log()), exposed.log().slice(-200));

    const found = cli(stateDir, ["key"]);
    check("kohlab key finds the stored key", found.out.includes("kohlab — generated by install.sh") === false && /^[0-9a-f]{48}$/m.test(found.out), found.out.slice(0, 120));

    const before = readFileSync(keyPath, "utf8").trim();
    const rotated = cli(stateDir, ["key", "rotate"]);
    const next = /^[0-9a-f]{48}$/m.exec(rotated.out)?.[0];
    check("kohlab key rotate issues a new one", !!next && next !== before, `before ${before.slice(0, 8)}…, printed ${String(next).slice(0, 8)}…`);
    check("the new key is what gets stored", readFileSync(keyPath, "utf8").trim() === next, "stored value differs from the printed one");
    check("rotate explains how to apply it", /systemctl restart/.test(rotated.out), rotated.out.slice(0, 200));
  } finally {
    stopServer(exposed);
  }

  // ── bound to loopback: the convenience stays ──────────────────────────────
  const local = await startServer({ port: 7822, works: "local", host: "127.0.0.1" });
  try {
    check("no key is generated on loopback", !existsSync(join(local.dir, "state", "key")));
    const anon = await fetch("http://127.0.0.1:7822/api/workspaces");
    check("a loopback-only server stays open, as documented", anon.status === 200, `got ${anon.status}`);
    check("and says which it is", /no key — loopback only/.test(local.log()), local.log().slice(-200));
  } finally {
    stopServer(local);
  }

  // ── a configured key still wins ───────────────────────────────────────────
  const keyed = await startServer({ port: 7823, works: "keyed", host: "0.0.0.0", extraEnv: { KOHLAB_KEY: "a-configured-key" } });
  try {
    check("a configured key is not overridden by a generated one", !existsSync(join(keyed.dir, "state", "key")));
    const anon = await fetch("http://127.0.0.1:7823/api/workspaces");
    check("the configured key is enforced", anon.status === 401, `got ${anon.status}`);
  } finally {
    stopServer(keyed);
  }

  console.log(`\n${passed} passed, ${failures.length} failed`);
  if (failures.length) {
    console.log("failed:\n" + failures.map((f) => `  - ${f}`).join("\n"));
    process.exit(1);
  }
  console.log("access bootstrap intact\n");
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
